# Generated by Django 5.1.6 on 2025-05-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clothes", "0002_cart_cartitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="ชื่อหมวดหมู่ (เช่น Evening Gowns, Casual Chic)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="ส่วนที่แสดงใน URL (ภาษาอังกฤษ, ไม่มีเว้นวรรค, ตัวเล็ก)",
                        max_length=120,
                        unique=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="รูปภาพหน้าปกของหมวดหมู่ (ควรมีขนาดเหมาะสมสำหรับแสดงผลเป็น Cover)",
                        null=True,
                        upload_to="category_covers/",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="คำอธิบายสั้นๆ (ถ้ามี)", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="แสดงหมวดหมู่นี้บนเว็บไซต์หรือไม่?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "หมวดหมู่ (Category)",
                "verbose_name_plural": "หมวดหมู่ (Categories)",
                "ordering": ["name"],
            },
        ),
    ]
