# Generated by Django 5.1.6 on 2025-05-11 13:11

import clothes.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clothes", "0004_herobanner"),
    ]

    operations = [
        migrations.AddField(
            model_name="herobanner",
            name="banner_type",
            field=models.CharField(
                choices=[("image", "Image Banner"), ("video", "Video Banner")],
                default="image",
                help_text="เลือกประเภทของ Banner",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="herobanner",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="ไฟล์ Video (แนะนำ .mp4, .webm, .ogg)",
                null=True,
                upload_to="hero_banners/videos/",
                validators=[clothes.models.validate_video_extension],
            ),
        ),
        migrations.AlterField(
            model_name="herobanner",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="รูปภาพปก (สำหรับ Image Banner หรือ Poster ของ Video)",
                null=True,
                upload_to="hero_banners/images/",
            ),
        ),
        migrations.AlterField(
            model_name="herobanner",
            name="is_active",
            field=models.BooleanField(
                default=False, help_text="เลือก True เพื่อให้ Banner นี้แสดงผล"
            ),
        ),
        migrations.AlterField(
            model_name="herobanner",
            name="link_url_name",
            field=models.CharField(
                blank=True,
                help_text="ชื่อ URL pattern ที่จะให้ Banner นี้ลิงก์ไป (เช่น clothes:new_arrivals)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="herobanner",
            name="order",
            field=models.PositiveIntegerField(default=0, help_text="ลำดับการแสดงผล"),
        ),
        migrations.AlterField(
            model_name="herobanner",
            name="subtitle",
            field=models.TextField(
                blank=True, help_text="คำโปรยหรือข้อความย่อย", null=True
            ),
        ),
        migrations.AlterField(
            model_name="herobanner",
            name="title",
            field=models.CharField(help_text="หัวข้อหลักบน Banner", max_length=200),
        ),
    ]
