# Generated by Django 5.1.6 on 2025-05-11 16:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clothes", "0005_herobanner_banner_type_herobanner_video_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "หมวดหมู่สินค้า",
                "verbose_name_plural": "หมวดหมู่สินค้า",
            },
        ),
        migrations.AlterModelOptions(
            name="clothing",
            options={
                "ordering": ["-created_at", "name"],
                "verbose_name": "สินค้าเสื้อผ้า",
                "verbose_name_plural": "สินค้าเสื้อผ้า",
            },
        ),
        migrations.RemoveField(
            model_name="clothing",
            name="available",
        ),
        migrations.AddField(
            model_name="clothing",
            name="available_for_rent",
            field=models.BooleanField(
                default=True, help_text="ชุดนี้พร้อมให้เช่าหรือไม่?"
            ),
        ),
        migrations.AddField(
            model_name="clothing",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="เลือกหมวดหมู่สำหรับชุดนี้",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clothes",
                to="clothes.category",
            ),
        ),
        migrations.AddField(
            model_name="clothing",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="clothing",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="ราคาเช่าต่อครั้ง/ต่อวัน (บาท)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="clothing",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="ส่วนที่แสดงใน URL (จะสร้างจากชื่ออัตโนมัติถ้าเว้นว่าง)",
                max_length=120,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="clothing",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="รูปภาพหน้าปกของหมวดหมู่",
                null=True,
                upload_to="category_covers/",
            ),
        ),
        migrations.AlterField(
            model_name="clothing",
            name="description",
            field=models.TextField(
                help_text="รายละเอียดชุด, เนื้อผ้า, ขนาด, คำแนะนำในการเช่า (ถ้ามี)"
            ),
        ),
        migrations.AlterField(
            model_name="clothing",
            name="image",
            field=models.ImageField(
                help_text="รูปภาพหลักของชุด", upload_to="clothing_images/"
            ),
        ),
        migrations.AlterField(
            model_name="clothing",
            name="name",
            field=models.CharField(help_text="ชื่อชุด", max_length=100),
        ),
    ]
